baseURL = 'https://mrrec00n.github.io/C00NsNEST/'
title = 'C00NsNEST'
languageCode = 'en'
theme='hello-friend-ng'


[params.Logo]
  logoText = "C00NsNEST"


[params]
  homeSubtitle = "Happy 🦝 reversing malware " 

  [[params.social]]
  name = "github"
  url = "https://github.com/MRreC00N"
  
  [[params.social]]
  name="twitter"
  url = "https://twitter.com/Mr_reC00N"

  [[params.social]]
  name="reddit"
  url = "https://www.reddit.com/user/Mr_reC00N"

  [[params.social]]
    name = "email"
    url  = "mailto:Mr_reC00N@proton.me"

[languages]
  [languages.en]
  title = "C00NsNEST"

  [languages.en.params]
  subtitle = "by MRreC00N"

[[menu.main]]
    identifier = "Categories"
    name       = "Categories"
    url        = "categories/"
[[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "posts/"
[[menu.main]]
    identifier = "Tags"
    name       = "Tags"
    url        = "tags/"

[params.footer]
    trademark = 2023
    rss = true
    copyright = true
    author = true
  
topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/MRreC00N\">MRreC00N</a>"
    ]

[params.portrait]
  path     = "enhanced.jpeg"
  alt      = "Portrait of a racoon"
  maxWidth = "300px"